// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95deLdMor02PueSBDaE1iNaqSMlZ79z8',
    appId: '1:351664151727:android:728dfd687811f6a5cb885a',
    messagingSenderId: '351664151727',
    projectId: 'shop-curso-31c74',
    databaseURL: 'https://shop-curso-31c74-default-rtdb.firebaseio.com',
    storageBucket: 'shop-curso-31c74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAaW6s_8SBUT7EGd4Uiou6bjD7mwsveG8',
    appId: '1:351664151727:ios:154299fb5215f41acb885a',
    messagingSenderId: '351664151727',
    projectId: 'shop-curso-31c74',
    databaseURL: 'https://shop-curso-31c74-default-rtdb.firebaseio.com',
    storageBucket: 'shop-curso-31c74.appspot.com',
    iosClientId:
        '351664151727-nhl0u2t2jb3mnq8arkrbs3m31kumgkr4.apps.googleusercontent.com',
    iosBundleId: 'com.example.shop',
  );
}
